# Identificação do projeto no Sonar (Cloud ou seu servidor)
sonar.projectKey=13SOAT_andromeda_tech-challenge-s1
# se for SonarCloud, pode usar organization
# sonar.organization=13SOAT-andromeda

sonar.projectName=Tech Challenge S1
sonar.projectVersion=1.0

# Fontes do código
sonar.sources=.
sonar.security.sources=.

# Excluir arquivos de teste da análise de fontes principais
sonar.exclusions=**/*_test.go,**/repository/**,**/router.go,**/model/**,**/handlers/**,**/internal/adapter/http/response/base_response.go,**/cmd/api/main.go,**/pkg/encryption/mock_hasher.go,**/internal/mocks/**, **/test/e2e/helper.go, **/internal/adapter/email/templates/**, **/Dockerfile

# Para testes
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/repository/**

# Relatório de cobertura (é gerado pelo go test)
sonar.go.coverage.reportPaths=coverage.out

# Codificação
sonar.sourceEncoding=UTF-8

# URL do servidor SonarQube (se for self-hosted)
# sonar.host.url=http://seu-servidor:9000

# Token — usado pelo CI
# sonar.login=${SONAR_TOKEN}
