apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base
  - ingress-nginx.yaml
  - config.yaml
  - postgres.yaml
  - ingress.yaml

patches:
  - target:
      kind: Deployment
      name: tech-challenge-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: tech-challenge-api:latest
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never