apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base
  - config.yaml

images:
  - name: tech-challenge-api
    newName: ECR_IMAGE

secretGenerator:
  - name: api-secrets
    behavior: replace
    envs:
      - .env.secrets

configMapGenerator:
  - name: api-config
    behavior: replace
    literals:
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=garagedb
      - DB_SSLMODE=require
      - DB_TIMEZONE=UTC
      - ENV=production
      - HTTP_PORT=8080
    envs:
      - .env.host

patches:
  - target:
      kind: Deployment
      name: tech-challenge-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      kind: Service
      name: tech-challenge-api-svc
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer