apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base
  - config.yaml

images:
  - name: tech-challenge-api
    newName: ECR_IMAGE

patches:
  - target:
      kind: Deployment
      name: tech-challenge-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      kind: Service
      name: tech-challenge-api-svc
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer