name: Deploy Infra

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/**'
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: AWS
    env:
      TF_VAR_lab_role_arn: ${{ vars.TF_VAR_LAB_ROLE_ARN }}
      TF_VAR_cluster_name: ${{ vars.EKS_CLUSTER }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./infra

      - name: Terraform Apply
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        working-directory: ./infra
