name: K8s Deploy (KIND)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - run: go build ./...

      - name: Build Docker image
        run: docker build -t tech-challenge-api:latest .

      - name: Deploy with Makefile
        run: |
          make up

      - name: Validate
        run: |
          kubectl get pods
          kubectl get hpa

      - name: Application logs
        run: |
          kubectl get pods
          POD=$(kubectl get pods -l app=tech-challenge-api -o jsonpath="{.items[0].metadata.name}")
          kubectl logs $POD

      - name: HPA status
        run: |
          kubectl describe hpa

