name: Deploy EKS

on:

  push:
    branches: [ main ]
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
      - 'k8s/**'
      - 'Dockerfile'

  pull_request:
    branches: [ main ]
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
      - 'k8s/**'
      - 'Dockerfile'

  workflow_run:
    workflows: ["Deploy Infra"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ASIARIUX34JE34W24VDI
          aws-secret-access-key: CkeSp7PmTaJYDvY3inuWQAmCUHjoyTAZnmMDoZ7C
          aws-session-token: IQoJb3JpZ2luX2VjEJP//////////wEaCXVzLXdlc3QtMiJHMEUCIEmfXROtnqeqiH0KS8GwjKm8nkLbTFfdx15ifN8AMBfpAiEA8CUPX/h2cGN9KwQyW+X6/VslBljiEqI7fLosg1toX7kqtgIIWxACGgwwODcyOTE1ODUwOTciDI13jpZfdcalYagAHyqTAt9TFLfUdYaflyk2c/6Qt2r8oGUPQFZAVOb5U00qH2ZY5oYiJCqw6CALUEIRs/uGgnFnpNkRAkDX4TPAd/ENLSZF88ouLeVhI4v4+TRo8GI+3+/3w1atFEhsvJ+yTr+66dGtmS0BYrS1pRsmMOCXg7kxUHUsco7pHKx8rszuDCR9AmqqVgF0DHOk12eLKVwOXYZcNxlT9wMYBiSYp/tVuPJ3ZTmyDOeKIk//B1Hy4oBDxAT5U/rjkIawSOdnOqRuC7tmjmXEyK7UacKnXBsflmbAGLL+putmTyAm9z2N+JsWyEjoy/DQ36cskKcp+e3cIYt8qoBna/7m7F3ThKWzSWGmcufDZ4gg8ceM4xCJaKM2MZE+MPzjq8sGOp0BwmeLvzzUkE7O3SiIcdC+Qt7SrCASH4OpirSHZxypmIK4+lr+2Kf20hqZAYGb5HZRfCWnSXfgAU7NPgZCxNUFFo+9N+ixev/9fy8vvOroqhKXd0DK+yOctuxSnu9/wHcEac/2I+g93JHe9rBKKeRiNQJGyZ8EFBwXzahZGRqY7duSAm+6a2RZ7+eQCJcO4o/ZJM0A8Ck60646eitIfQ==
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.AWS_ECR_REPO }}
          IMAGE_TAG: latest
        run: |
          # Build
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Deploy to K8s
        run: |
          RDS_ADDRESS=$(aws rds describe-db-instances --query "DBInstances[0].Endpoint.Address" --output text)
          
          kubectl create secret generic api-secrets \
            --from-literal=DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --from-literal=JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --from-literal=ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}" \
            --from-literal=MAILTRAP_TOKEN="${{ secrets.MAILTRAP_TOKEN }}" \
            --dry-run=client -o yaml | kubectl apply -f -
          
          
          kubectl kustomize k8s/overlays/aws | \
            sed "s|ECR_IMAGE:latest|${{ steps.login-ecr.registry }}/${{ vars.AWS_ECR_REPO }}:latest|g" | \
            kubectl apply -f -
          
          kubectl patch configmap api-config --type merge -p "{\"data\":{\"DB_HOST\":\"$RDS_ADDRESS\"}}"
          
          # 4. Reinicia o deploy para garantir atualização
          kubectl rollout restart deployment tech-challenge-api